global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']  # or 'localhost:8080' if not using Docker
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]

