spring:
  flyway:
    enabled: 'true'
    locations: classpath:db/migration
  datasource:
    username: root
    password: root12345
    url: jdbc:mysql://localhost:3306/testdb?useSSL=false&serverTimezone=UTC

  jpa:
    hibernate:
      ddl-auto: validate